### ISSUE TITLE
Add id to model for unique device

### ISSUE THREAD

**Issue by dinki** [mverleun/RTL433-to-mqtt#1]
Hi.  First off, thanks!  I got this up and running with zero problem and minimum effort.  I have a bunch of water sensors that all show up as the same model but they all have unique ids.  I'd like to be able to change the mqtt topic to include the additional id to the model name to make for unique messages.

I've tried adding this after the check if 'model' is in the JSON:

```
if "id" in item:
    subtopic=subtopic+ '-' + str(value)
```

but my python skills are obviously not up to par.  Can someone tell me how to mod the script to make the devices unique? Thanks again!

**Comment by mverleun** [comment]
I would assume that something like this would work:
```
            for item in json_dict:
                value = json_dict[item]
                if "model" in item:
                    subtopic=value
                if "id" in item:
                    subtopic=subtopic + '-' + value
```

**Comment by dinki** [comment]
@mverleun 

I got it.  I had to set subtopic="" right before the for loop as it was undefined for some reason even though model was in the topic.  At any rate, thanks again!

**Comment by suprimex** [comment]
> @mverleun
> 
> I got it. I had to set subtopic="" right before the for loop as it was undefined for some reason even though model was in the topic. At any rate, thanks again!

subtopic=""  still absent from code.

In my case "model " is absent but id present, so 
subtopic += ...
 - throw error for me.

**Comment by dinki** [comment]
I'm not sure but I can say that this does not work for me all the time on start.  I sometimes have to restart for it to pick up the id.  In short, I can get it to work, but not reliably.  I'm not a programmer but merely a hacker.  Would be nice if someone who knew what they were doing would incorporate this though.
